### ISSUE TITLE
Correção de titulo da Unidade

### ISSUE THREAD

**Issue by PedroHenrique2077** [fga-eps-mds/2022-2-CAPJu-Interface#11]
## Descrição
Ao clicar em visualizar administradores, o titulo apresentado não condiz com a Unidade

#### Caminho:

Unidades > coluna ações > clicar no olho

## Tarefas
- [ ] Alterar o titulo apresentado

## Critérios de Aceitação
- [ ] Ao clicar em visualizar administradores da Unidade o titulo deve estar de acordo com a Unidade 

#### Print da tela que precisa ser arrumada
![image](https://user-images.githubusercontent.com/90395870/202870345-49d99719-2411-4885-80dd-b5fdf0d594ac.png)
![image](https://user-images.githubusercontent.com/90395870/202870226-fdd75315-f7a6-438d-bdef-e0a85d6dc6ce.png)

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Interface/11?planning-poker) with Zenhub @AntonioAldisio @DaviAntonio @luderibeiro @vitorAlves7
