### ISSUE TITLE
Correção da listagem de administradores da Unidade

### ISSUE THREAD

**Issue by PedroHenrique2077** [fga-eps-mds/2022-2-CAPJu-Interface#12]
## Descrição

O sistema só mostra os administradores da Unidade depois de algumas tentativas de visualizar

#### Caminho:

Unidades > coluna ações > clicar no olho

## Tarefas
- [ ] Fazer o sistema retornar os nomes dos administradores

## Critérios de Aceitação
- [ ] Mostrar administradores de uma Unidade ao clicar apenas uma vez no botão visualizar administradores

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Interface/12?planning-poker) with Zenhub @AntonioAldisio @DaviAntonio @luderibeiro @vitorAlves7
