### ISSUE TITLE
[HU - 01] - Gerenciar anotação

### ISSUE THREAD

**Issue by AntonioAldisio** [fga-eps-mds/2022-2-CAPJu-Interface#41]
## Descrição

Como estagiário/servidor/diretor,
eu quero gerenciar uma anotação entre duas etapas de um fluxo,
para que ter controle das informações sobre o progresso de um processo.

### Critérios gerais

- [ ] Deve haver um elemento para interagir com as anotações
- [ ] Tamanho da anotação deve ter 100 caracteres disponíveis.
- [ ] Ter uma janela para confirmar operações em anotações
- [ ] Deve ser possível editar uma anotação
- [ ] Deve ser possível deletar uma anotação

#### Criar uma anotação

Dado que o estagiário, servidor ou diretor estão autenticados, e existe um fluxo sem anotações entre as suas etapas, 
- [ ] quando se clica para criar uma anotação entre duas etapas,
- [ ] digita-se uma anotação com até 100 caracteres,
- [ ] e solicita-se a criação,
- [ ] então a anotação deve ser salva no sistema.

#### Criar uma anotação inválida

Dado que o estagiário, servidor ou diretor estão autenticados, e existe um fluxo sem anotações entre as suas etapas,
- [ ] quando se clica para criar uma anotação entre duas etapas,
- [ ] digita-se uma anotação vazia ou com mais de 100 caracteres,
- [ ] e solicita-se a criação,
- [ ] então a anotação não deve ser salva no sistema e o usuário deve ser informado do erro.

#### Apagando uma anotação

Dado que o estagiário, servidor ou diretor estão autenticados, e existe um fluxo com uma ou mais anotações entre as suas etapas,
- [ ] quando se clica para apagar uma anotação,
- [ ] então a anotação deve ser removida do sistema.

#### Modificando o conteúdo de uma anotação

Dado que o estagiário, servidor ou diretor estão autenticados, e existe um fluxo com uma ou mais anotações entre as suas etapas,
- [ ] quando se clica para editar uma anotação,
- [ ] digita-se uma mensagem com até 100 caracteres,
- [ ] e solicita-se a modificação,
- [ ] então a anotação deve ser modificada.

#### Modificando o conteúdo de uma anotação de maneira inválida

Dado que o estagiário, servidor ou diretor estão autenticados, e existe um fluxo com uma ou mais anotações entre as suas etapas,
- [ ] quando se clica para editar uma anotação, digita-se uma mensagem vazia ou com mais de 100 caracteres,
- [ ] e solicita-se a modificação,
- [ ] então a anotação não deve ser modificada, e o usuário deve ser informado do erro.

**Comment by AntonioAldisio** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Interface/41?planning-poker) with Zenhub @DaviAntonio @ilus1 @vitorAlves7

**Comment by DaviAntonio** [comment]
Reescreveu-se a história, adicionando-se cenários de teste para auxiliar nos testes de aceitação.

**Comment by DaviAntonio** [comment]
Atualizar limites das anotações devido a fga-eps-mds/2022-2-CAPJu-Doc#124
