### ISSUE TITLE
[Tarefa - 01] - Prototipação das telas de gerenciamento de anotação

### ISSUE THREAD

**Issue by AntonioAldisio** [fga-eps-mds/2022-2-CAPJu-Interface#42]
## Descrição.

Prototipação de alta fidelidade para as ações relacionadas ao gerenciamento de anotação.

## Critérios de aceitação

- [x] Tela de confirmação de operação
- [x] Tela de edição da anotação
- [x] Demonstrar o posicionamento dos elementos interativos.

**Comment by AntonioAldisio** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Interface/42?planning-poker) with Zenhub @DaviAntonio @ilus1 @vitorAlves7 @chaydson @LucasLopesFrazao

**Comment by LucasLopesFrazao** [comment]
O link do prototipo se encontra em: [Figma](https://www.figma.com/file/RiXVNKDjh79kkChz1LHnph/MDS-(CAPju)?node-id=0%3A1&t=kHXQSPijg4X3bhVG-1)

**Comment by chaydson** [comment]
Telas prototipadas:
![image](https://user-images.githubusercontent.com/90580219/205198177-caf8d889-5585-4c1b-841d-7d36dbfe1701.png)
![image](https://user-images.githubusercontent.com/90580219/205198110-08befcc7-cb4b-45c0-80d6-fc7591cb0ec7.png)
