### ISSUE TITLE
[Tarefa - 02] Edição de anotação

### ISSUE THREAD

**Issue by ilus1** [fga-eps-mds/2022-2-CAPJu-Interface#43]
## Descrição.
Deve ser possível editar a anotação após interagir com o elemento adequado.

## Critérios de aceitação

- [ ] Deve ser possível interagir com o elemento de edição
- [ ] Uma tela de edição deve ser exibida para a alteração da anotação selecionada.
- [ ] Após confirmada a alteração, deverá aparecer uma tela de confirmação da operação.

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Interface/43?planning-poker) with Zenhub @DaviAntonio @vitorAlves7

**Comment by AntonioAldisio** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Interface/43?planning-poker) with Zenhub @luderibeiro
