### ISSUE TITLE
[Tarefa 03] Deletar uma anotação

### ISSUE THREAD

**Issue by ilus1** [fga-eps-mds/2022-2-CAPJu-Interface#44]
## Descrição.
Deve ser possível deletar a anotação após interagir com o elemento adequado.

## Critérios de aceitação

- [ ] Deve ser possível interagir com o elemento de remoção.
- [ ] Após confirmada a remoção, deverá aparecer uma tela de confirmação da operação.

**Comment by AntonioAldisio** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Interface/44?planning-poker) with Zenhub @DaviAntonio @ilus1 @luderibeiro @vitorAlves7
