### ISSUE TITLE
[Tarefa - 05] Botão de criação de anotação

### ISSUE THREAD

**Issue by ilus1** [fga-eps-mds/2022-2-CAPJu-Interface#45]
## Descrição.
Deve ser possível criar a anotação sem que seja necessário mover o processo entre etapas.

## Critérios de aceitação

- [x] Deve ser possível interagir com o elemento de criação
- [x] Uma tela deve ser exibida para a criação da anotação.
- [x] Após confirmada a criação, deverá aparecer uma tela de confirmação da operação.

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Interface/45?planning-poker) with Zenhub @DaviAntonio @vitorAlves7

**Comment by AntonioAldisio** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Interface/45?planning-poker) with Zenhub @luderibeiro
