### ISSUE TITLE
Correção do componente de estatística 

### ISSUE THREAD

**Issue by PedroHenrique2077** [fga-eps-mds/2022-2-CAPJu-Interface#7]
## Descrição

Ao retornar, pela seta do navegador, para visualizar estatísticas o componente demora para aparecer

#### Caminho:

Fluxos > visualizar estatísticas > clicar no número de uma estatística

## Tarefas
- [ ] Reduzir o tempo de renderização do componente

## Critérios de Aceitação
- [ ] Ao retornar a página para visualizar estatísticas, o componente deve ser renderizado no tempo padrão de componentes de uma SPA.

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Interface/7?planning-poker) with Zenhub @AntonioAldisio @DaviAntonio @luderibeiro @vitorAlves7
