### ISSUE TITLE
Refatoração no espaçamento da modal de edição de processo 

### ISSUE THREAD

**Issue by chaydson** [fga-eps-mds/2022-2-CAPJu-Interface#8]
## Descrição
Diminuir espaçamento entre os componentes na modal de edição de processo para que seja mais fácil e agradável a usabilidade.

#### Caminhos: 
Fluxos > Visualizar estatísticas > clicar no numero de uma estatistica > icone de lápis
Fluxos > Visualizar estatísticas > clicar no numero de uma estatistica > icone de lixeira

## Tarefas
- [ ] Diminuir o espaçamento entre os componentes

## Critérios de Aceitação
- [ ] Dar um espaçamento adequado aos componentes da modal

#### Print da tela que precisa ser arrumada
![image](https://user-images.githubusercontent.com/90580219/202868444-7cc30abd-8a1d-44e4-a905-a4cb0264ab8b.png)
![image](https://user-images.githubusercontent.com/90580219/202868460-08ec9c7e-4527-4ec5-ac93-13509ce94558.png)

**Comment by LucasLopesFrazao** [comment]
Não mexer nessa issue, ao entrar em estatistica, gera uma requisição infinita, fazendo a memoria ir pro espaço.

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Interface/8?planning-poker) with Zenhub @AntonioAldisio @DaviAntonio @luderibeiro @vitorAlves7
