### ISSUE TITLE
Correção no componente do fluxo

### ISSUE THREAD

**Issue by PedroHenrique2077** [fga-eps-mds/2022-2-CAPJu-Interface#9]
## Descrição
Ao entrar na página de visualização do fluxo, o mesmo demora para ser renderizado

#### Caminho:
Fluxos > Visualizar estatísticas > clicar no numero de uma estatística > botão de olho

## Tarefas
- [ ] Reduzir o tempo de renderização do fluxo

## Critérios de Aceitação
- [ ] O fluxo deve ser renderizado no tempo padrão de componentes de uma SPA

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-Interface/9?planning-poker) with Zenhub @AntonioAldisio @DaviAntonio @luderibeiro @vitorAlves7
